_base_ = ['../_base_/models/efficientnet_b0.py',
          '../_base_/datasets/imagenet_bs32.py',
          '../_base_/schedules/imagenet_bs256.py',
          '../_base_/default_runtime.py']

# Model config
model = dict(type='ImageClassifier',
             backbone=dict(type='EfficientNet',
                           arch='b0'),
             neck=dict(type='GlobalAveragePooling'),
             head=dict(type='LinearClsHead',
                       num_classes=36,
                       in_channels=1280,
                       loss=dict(type='CrossEntropyLoss',
                                 loss_weight=1.0),
                       topk=(1,)))

# Dataset config
dataset_type = 'ImageNet'
img_norm_cfg = dict(mean=[127.5, 127.5, 127.5],
                    std=[127.5, 127.5, 127.5],
                    to_rgb=True)

train_pipeline = [dict(type='LoadImageFromFile'),
                  dict(type='Albu',
                       transforms=[dict(type='OneOf',
                                        p=1.0,
                                        transforms=[dict(type='FancyPCA',
                                                         always_apply=False,
                                                         p=1.0,
                                                         alpha=1.0),
                                                    dict(type='RandomBrightnessContrast',
                                                         always_apply=False,
                                                         p=1.0,
                                                         brightness_limit=(-0.3, 0.4),
                                                         contrast_limit=(-0.25, 0.2),
                                                         brightness_by_max=True),
                                                    dict(type='RandomGamma',
                                                         always_apply=False,
                                                         p=1.0,
                                                         gamma_limit=(30, 400),
                                                         eps=None),
                                                    dict(type='RandomToneCurve',
                                                         always_apply=False,
                                                         p=1.0,
                                                         scale=3.0),
                                                    dict(type='RGBShift',
                                                         always_apply=False,
                                                         p=1.0,
                                                         r_shift_limit=(-100, 100),
                                                         g_shift_limit=(-100, 100),
                                                         b_shift_limit=(-100, 100))]),
                                   dict(type='OneOf',
                                        p=1.0,
                                        transforms=[dict(type='GaussNoise',
                                                         always_apply=False,
                                                         p=1.0,
                                                         var_limit=(0.0, 100.0),
                                                         per_channel=True,
                                                         mean=0),
                                                    dict(type='ISONoise',
                                                         always_apply=False,
                                                         p=1.0,
                                                         intensity=(0.1, 0.3),
                                                         color_shift=(0.0, 1.0)),
                                                    dict(type='MultiplicativeNoise',
                                                         always_apply=False,
                                                         p=1.0,
                                                         multiplier=(0.9, 1.1),
                                                         per_channel=False,
                                                         elementwise=True),
                                                    dict(type='RandomRain',
                                                         always_apply=False,
                                                         p=1.0,
                                                         slant_lower=-10,
                                                         slant_upper=10,
                                                         drop_length=20,
                                                         drop_width=1,
                                                         drop_color=(200, 200, 200),
                                                         blur_value=1,
                                                         brightness_coefficient=0.7,
                                                         rain_type='heavy'),
                                                    dict(type='RandomShadow',
                                                         always_apply=False,
                                                         p=1.0,
                                                         shadow_roi=(0.0, 0.0, 1.0, 1.0),
                                                         num_shadows_lower=1,
                                                         num_shadows_upper=5,
                                                         shadow_dimension=3)]),
                                   dict(type='OneOf',
                                        p=1.0,
                                        transforms=[dict(type='Affine',
                                                         always_apply=False,
                                                         p=1.0,
                                                         interpolation=1,
                                                         cval=0,
                                                         mode=1,
                                                         scale={'x':(0.8, 1.2),
                                                                'y':(0.8, 1.2)},
                                                         translate_percent=None,
                                                         translate_px={'x':(0, 0),
                                                                       'y':(0, 0)},
                                                         rotate=(-5, 5),
                                                         fit_output=False,
                                                         shear={'x':(-1, 1),
                                                                'y':(-1, 1)},
                                                         cval_mask=0),
                                                    dict(type='ShiftScaleRotate',
                                                         always_apply=False,
                                                         p=1.0,
                                                         shift_limit_x=(-0.2, 0.2),
                                                         shift_limit_y=(-0.15, 0.1),
                                                         scale_limit=(-0.19999999999999996, 0.19999999999999996),
                                                         rotate_limit=(-5, 5),
                                                         interpolation=1,
                                                         border_mode=1,
                                                         value=None,
                                                         mask_value=None)]),
                                   dict(type='OneOf',
                                        p=1.0,
                                        transforms=[dict(type='Blur',
                                                         always_apply=False,
                                                         p=1.0,
                                                         blur_limit=(1, 5)),
                                                    dict(type='GaussianBlur',
                                                         always_apply=False,
                                                         p=1.0,
                                                         blur_limit=(1, 7),
                                                         sigma_limit=(0, 0)),
                                                    dict(type='RandomFog',
                                                         always_apply=False,
                                                         p=1.0,
                                                         fog_coef_lower=1.0,
                                                         fog_coef_upper=1.0,
                                                         alpha_coef=0.5),
                                                    dict(type='Downscale',
                                                         always_apply=False,
                                                         p=1.0,
                                                         scale_min=0.9,
                                                         scale_max=0.95,
                                                         interpolation=0),
                                                    dict(type='ImageCompression',
                                                         always_apply=False,
                                                         p=1.0,
                                                         quality_lower=20,
                                                         quality_upper=70,
                                                         compression_type=0),
                                                    dict(type='MotionBlur',
                                                         always_apply=True,
                                                         p=1.0,
                                                         blur_limit=(3, 6))])],
                       keymap={'img': 'image',
                               'gt_bboxes': 'bboxes'},
                       update_pad_shape=False),
                  dict(type='Resize',
                       size=(224, 224),
                       interpolation='bicubic',
                       backend='pillow'),
                  dict(type='Normalize',
                       **img_norm_cfg),
                  dict(type='ImageToTensor',
                       keys=['img']),
                  dict(type='ToTensor',
                       keys=['gt_label']),
                  dict(type='Collect',
                       keys=['img', 'gt_label'])]

val_pipeline = [dict(type='LoadImageFromFile'),
                dict(type='Albu',
                     transforms=[dict(type='OneOf',
                                      p=1.0,
                                      transforms=[dict(type='FancyPCA',
                                                       always_apply=False,
                                                       p=1.0,
                                                       alpha=1.0),
                                                  dict(type='RandomBrightnessContrast',
                                                       always_apply=False,
                                                       p=1.0,
                                                       brightness_limit=(-0.3, 0.4),
                                                       contrast_limit=(-0.25, 0.2),
                                                       brightness_by_max=True),
                                                  dict(type='RandomGamma',
                                                       always_apply=False,
                                                       p=1.0,
                                                       gamma_limit=(30, 400),
                                                       eps=None),
                                                  dict(type='RandomToneCurve',
                                                       always_apply=False,
                                                       p=1.0,
                                                       scale=3.0),
                                                  dict(type='RGBShift',
                                                       always_apply=False,
                                                       p=1.0,
                                                       r_shift_limit=(-100, 100),
                                                       g_shift_limit=(-100, 100),
                                                       b_shift_limit=(-100, 100))]),
                                 dict(type='OneOf',
                                      p=1.0,
                                      transforms=[dict(type='GaussNoise',
                                                       always_apply=False,
                                                       p=1.0,
                                                       var_limit=(0.0, 100.0),
                                                       per_channel=True,
                                                       mean=0),
                                                  dict(type='ISONoise',
                                                       always_apply=False,
                                                       p=1.0,
                                                       intensity=(0.1, 0.3),
                                                       color_shift=(0.0, 1.0)),
                                                  dict(type='MultiplicativeNoise',
                                                       always_apply=False,
                                                       p=1.0,
                                                       multiplier=(0.9, 1.1),
                                                       per_channel=False,
                                                       elementwise=True),
                                                  dict(type='RandomRain',
                                                       always_apply=False,
                                                       p=1.0,
                                                       slant_lower=-10,
                                                       slant_upper=10,
                                                       drop_length=20,
                                                       drop_width=1,
                                                       drop_color=(200, 200, 200),
                                                       blur_value=1,
                                                       brightness_coefficient=0.7,
                                                       rain_type='heavy'),
                                                  dict(type='RandomShadow',
                                                       always_apply=False,
                                                       p=1.0,
                                                       shadow_roi=(0.0, 0.0, 1.0, 1.0),
                                                       num_shadows_lower=1,
                                                       num_shadows_upper=5,
                                                       shadow_dimension=3)]),
                                 dict(type='OneOf',
                                      p=1.0,
                                      transforms=[dict(type='Affine',
                                                       always_apply=False,
                                                       p=1.0,
                                                       interpolation=1,
                                                       cval=0,
                                                       mode=1,
                                                       scale={'x':(0.8, 1.2),
                                                              'y':(0.8, 1.2)},
                                                       translate_percent=None,
                                                       translate_px={'x':(0, 0),
                                                                     'y':(0, 0)},
                                                       rotate=(-5, 5),
                                                       fit_output=False,
                                                       shear={'x':(-1, 1),
                                                              'y':(-1, 1)},
                                                       cval_mask=0),
                                                  dict(type='ShiftScaleRotate',
                                                       always_apply=False,
                                                       p=1.0,
                                                       shift_limit_x=(-0.2, 0.2),
                                                       shift_limit_y=(-0.15, 0.1),
                                                       scale_limit=(-0.19999999999999996, 0.19999999999999996),
                                                       rotate_limit=(-5, 5),
                                                       interpolation=1,
                                                       border_mode=1,
                                                       value=None,
                                                       mask_value=None)]),
                                 dict(type='OneOf',
                                      p=1.0,
                                      transforms=[dict(type='Blur',
                                                       always_apply=False,
                                                       p=1.0,
                                                       blur_limit=(1, 5)),
                                                  dict(type='GaussianBlur',
                                                       always_apply=False,
                                                       p=1.0,
                                                       blur_limit=(1, 7),
                                                       sigma_limit=(0, 0)),
                                                  dict(type='RandomFog',
                                                       always_apply=False,
                                                       p=1.0,
                                                       fog_coef_lower=1.0,
                                                       fog_coef_upper=1.0,
                                                       alpha_coef=0.5),
                                                  dict(type='Downscale',
                                                       always_apply=False,
                                                       p=1.0,
                                                       scale_min=0.9,
                                                       scale_max=0.95,
                                                       interpolation=0),
                                                  dict(type='ImageCompression',
                                                       always_apply=False,
                                                       p=1.0,
                                                       quality_lower=20,
                                                       quality_upper=70,
                                                       compression_type=0),
                                                  dict(type='MotionBlur',
                                                       always_apply=True,
                                                       p=1.0,
                                                       blur_limit=(3, 6))])],
                     keymap={'img': 'image',
                             'gt_bboxes': 'bboxes'},
                     update_pad_shape=False),
                dict(type='Resize',
                     size=(224, 224),
                     interpolation='bicubic',
                     backend='pillow'),
                dict(type='Normalize',
                     **img_norm_cfg),
                dict(type='ImageToTensor',
                     keys=['img']),
                dict(type='Collect',
                     keys=['img'])]

test_pipeline = [dict(type='LoadImageFromFile'),
                 dict(type='Resize',
                      size=(224, 224),
                      interpolation='bicubic',
                      backend='pillow'),
                 dict(type='Normalize',
                      **img_norm_cfg),
                 dict(type='ImageToTensor',
                      keys=['img']),
                 dict(type='Collect',
                      keys=['img'])]

data = dict(samples_per_gpu=48,
            workers_per_gpu=24,
            train=dict(type=dataset_type,
                       data_prefix='/tmp/front_id_card_classification_id/train/image',
                       ann_file='/tmp/front_id_card_classification_id/train/imagenet_label.txt',
                       pipeline=train_pipeline,
                       classes='/tmp/front_id_card_classification_id/imagenet_class_name.txt'),
            val=dict(type=dataset_type,
                     data_prefix='/tmp/front_id_card_classification_id/val/image',
                     ann_file='/tmp/front_id_card_classification_id/val/imagenet_label.txt',
                     pipeline=val_pipeline,
                     classes='/tmp/front_id_card_classification_id/imagenet_class_name.txt'),
            test=dict(type=dataset_type,
                           data_prefix='/tmp/front_id_card_classification_id/val/image',
                           ann_file='/tmp/front_id_card_classification_id/val/imagenet_label.txt',
                           pipeline=test_pipeline,
                           classes='/tmp/front_id_card_classification_id/imagenet_class_name.txt'))
evaluation = dict(interval=1,
                  save_best='auto',
                  metric='accuracy')
# Schedule config
runner = dict(max_epochs=1000)

# Runtime config
checkpoint_config = None
log_config = dict(interval=1,
                  hooks=[dict(type='TextLoggerHook'),
                         dict(type='TensorboardLoggerHook')])